import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { Store, StreamFault } from '../stream/store.ts';
import { browserWorkspace } from '../runtime/browser-files.ts';
import { browserPacket, payload } from '../adapters/browser/index.ts';
import { createReplyServer } from '../runtime/reply-tool.ts';
import { readEvidence,readEvidenceChanges,readEvidenceFragment,downloadEvidence,validateEvidenceReferences,toWireSelector,modelEvidenceReferences } from '../runtime/browser-evidence.ts';
test('actual MCP delta/current/history/reference custody survives restart and refuses all malformed identity/bounds without final fence',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'carbon-evidence-owned-')),sentinel=path.join(root,'separate');fs.writeFileSync(sentinel,'unchanged');
 try{
 fs.mkdirSync(path.join(root,'work'));fs.mkdirSync(path.join(root,'checkout'));fs.writeFileSync(path.join(root,'checkout','AGENTS.md'),'Synthetic guidance');
 const store=Store.open(path.join(root,'store')),conversation='cohort:ticket:DEMO-1',workspace=browserWorkspace({work:path.join(root,'work'),conversationId:conversation,checkout:path.join(root,'checkout')});
 
 const p=browserPacket({account:'cohort',ticket_key:'DEMO-1',submission_id:crypto.randomUUID(),consultant:{id:'alice',name:'Alice'},input_kind:'start',body:'',accepted_at:new Date().toISOString(),position:'00000000000000000001'});const r=payload({store,agent:'fixture-agent',account:'cohort'},[p]).entries[0].record;store.capture(r);store.release(r,{thread_id:'thread',turn_id:'release',released_at:new Date().toISOString(),hold_applies:false});
 store.activeBrowserReply={conversation_id:conversation,release_id:'release',native_turn_id:'native',workspace};
 const source=path.join(workspace.evidence,'comments.json'),bytes=Buffer.from(JSON.stringify({startAt:2,total:3,comments:[{id:'3',body:'actual original',updated:'2026-10-07'}]}));fs.writeFileSync(source,bytes,{mode:0o400});fs.writeFileSync(source+'.provenance.json',JSON.stringify({mediaType:'application/json',size:bytes.length,provenance:{url:'https://jira.invalid/rest/api/2/issue/DEMO-1/comment?startAt=2',fetchedAt:'2026-10-07T00:00:00Z'}}),{mode:0o400});
 const server=createReplyServer({store,agent:'fixture-agent'});const call=async(name:string,args:unknown)=>{const response=await server.handle({jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}}) as {result?:{isError?:boolean;structuredContent?:unknown};error?:unknown};return response;};
 const itemId=crypto.randomUUID(),changeId=crypto.randomUUID(),delta={changeId,add:[{itemId,label:'Comments page 2',path:source,selector:toWireSelector({kind:'field',pointer:'/comments/0/body'}),note:null,basis:[],assumptions:[],producerPath:null}],remove:[],note:'Inspect the retained late comment'};
 const published=await call('evidence_present',delta);assert.notEqual(published.result?.isError,true,JSON.stringify(published));assert.equal(store.readRequest('release'),null);
 const page=readEvidence(store,conversation),anchor=page.anchor;assert.equal(page.items[0].origin,'original');assert.equal(page.items[0].label,'Comments page 2');assert.equal(readEvidenceChanges(store,conversation).changes.length,1);
 const fragment=readEvidenceFragment(store,conversation,itemId,{kind:'field',pointer:'/comments/0/body'},0,0,100);assert.equal(fragment.content.kind,'json');assert.equal('value' in fragment.content&&fragment.content.value,'actual original');assert.deepEqual(downloadEvidence(store,conversation,page.items[0].sourceId).bytes,bytes);assert.equal(validateEvidenceReferences(store,conversation,[fragment.reference]).length,1);
 await call('evidence_present',delta);assert.equal(readEvidenceChanges(store,conversation).changes.length,1);
 const bad=await call('evidence_present',{...delta,changeId:crypto.randomUUID(),add:[{...delta.add[0],itemId:crypto.randomUUID(),selector:toWireSelector({kind:'field',pointer:'/missing'})}],remove:[{itemId:crypto.randomUUID(),reason:'missing'}]});assert.equal(bad.result?.isError,true);assert.equal(readEvidence(store,conversation).items.length,1);
 await call('evidence_present',{changeId:crypto.randomUUID(),add:[],remove:[{itemId,reason:'Superseded by the exact newer source'}],note:null});assert.equal(readEvidence(store,conversation).items.length,0);assert.equal(readEvidence(store,conversation,{anchor}).items.length,1);assert.equal(validateEvidenceReferences(store,conversation,[fragment.reference]).length,1,'removed immutable history remains referenceable');
 const reopened=Store.open(path.join(root,'store'));assert.equal(readEvidence(reopened,conversation).items.length,0);assert.equal(readEvidence(reopened,conversation,{anchor}).items.length,1);assert.equal(readEvidenceChanges(reopened,conversation).changes[1].removed[0].reason,'Superseded by the exact newer source');
 assert.throws(()=>validateEvidenceReferences(reopened,'cohort:ticket:DEMO-2',[fragment.reference]),StreamFault);assert.throws(()=>validateEvidenceReferences(reopened,conversation,[{...fragment.reference,sha256:'0'.repeat(64)}]),StreamFault);
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aRZkAAAAASUVORK5CYII=','base64'),imagePath=path.join(workspace.analysis,'derived-image.png');fs.writeFileSync(imagePath,png);const imageId=crypto.randomUUID();assert.notEqual((await call('evidence_present',{changeId:crypto.randomUUID(),add:[{itemId:imageId,label:'Derived image',path:imagePath,selector:toWireSelector({kind:'region',x:0,y:0,width:1,height:1}),note:'Synthetic full original image input',basis:[{...fragment.reference,selector:toWireSelector(fragment.reference.selector)}],assumptions:[],producerPath:null}],remove:[],note:null})).result?.isError,true);const imageFragment=readEvidenceFragment(store,conversation,imageId,{kind:'region',x:0,y:0,width:1,height:1});const model=modelEvidenceReferences(store,conversation,[imageFragment.reference],workspace);assert.equal(model.inputs[0].type,'localImage');assert.deepEqual(fs.readFileSync(model.inputs[0].path),png);assert.deepEqual(model.references[0].reference.selector,{kind:'region',x:0,y:0,width:1,height:1});assert.equal(model.references[0].origin,'analysis');assert.throws(()=>validateEvidenceReferences(store,conversation,[{...fragment.reference,sourceId:'wrong',representationId:'wrong',representationVersion:'wrong',sha256:'0'.repeat(64)}]),(e:unknown)=>e instanceof StreamFault&&e.faults.length>=4);
 store.activeBrowserReply=null;assert.equal((await call('evidence_present',delta)).result?.isError,true);assert.equal(fs.readFileSync(sentinel,'utf8'),'unchanged');
 }finally{fs.rmSync(root,{recursive:true,force:true});assert.equal(fs.existsSync(root),false);}
});
